config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  resources :users, only: %i[new create]
  resources :boards, only: %i[index new create show edit update destroy] 
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }
  acts_as_taggable_on :tags
  mount_uploader :board_image, BoardImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  # ユーザー名は10文字以下
  validates :name, presence: true, length: { maximum: 10 }

  # パスワードは4文字以上8文字以下
  validates :password, length: { in: 4..8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true, uniqueness: true
  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  add_flash_types :success, :danger

  private

  def not_authenticated
    redirect_to login_path, danger: t('defaults.flash_message.require_login')
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @boards = Board.includes(:user)
    if params[:tag]
      @boards = Board.tagged_with(params[:tag])
    else
      @boards = Board.all
    end
  
    @boards = @boards.order(created_at: :desc) 
  end
  
  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: t('defaults.flash_message.created', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path, success: t('defaults.flash_message.updated', item: Board.model_name.human) 
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated', item: Board.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    redirect_to boards_path, success: t('defaults.flash_message.deleted', item: Board.model_name.human), status: :see_other
  end

  private

  def board_params
    params.require(:board).permit(:body, :board_image, :board_image_cache, :tag_list)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to boards_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('.success')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to boards_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/boards/_board.html.erb
<div class="w-1/3 sm:w-1/3 lg:w-1/3 m-0">
  <div id="board-id-<%= board.id %>" class="border-0">
    <div class="bg-white overflow-hidden border-0">
      <div class="relative w-full" style="aspect-ratio: 1 / 1;">
        <%= link_to board_path(board) do %>
          <%= image_tag board.board_image_url.presence || 'board_placeholder.png', class: "absolute inset-0 w-full h-full object-cover p-1 border-0 outline-0" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<div class='container mx-auto px-4'>
  <div class='md:w-1/2 mx-auto'>
    
    <div class="text-left mb-4"> 
      <p class="text-sm text-gray-800"><%= @board.user.name %></p> 
    </div>

    <%= image_tag @board.board_image_url, class: 'object-contain w-full h-auto mx-auto mb-4' if @board.board_image_url.present? %>

    <%= form_with(model: @board, local: true) do |form| %>
      <div class="mb-6">
        <%= form.label :tag_list, "タグ（カンマ区切りで入力）", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :tag_list, value: @board.tag_list.join(", "), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "タグをカンマで区切って入力" %>
      </div>
      <div class="mb-6">
        <%= form.label :body, "おすすめポイント", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-6">
        <%= form.label :board_image, "画像の再アップロード（必要であれば）", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.file_field :board_image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        <%= form.hidden_field :board_image_cache %>
      </div>

      <div class="flex justify-end">
        <%= form.submit '更新', class: 'btn bg-gray-200 hover:bg-gray-300 text-black font-bold py-2 px-4 rounded' %>
      </div>
    <% end %>

    <div class="text-center mb-4">
      <%= l @board.created_at, format: '%Y/%m/%d %H:%M' %>
    </div>
    <div class='text-center'>
      <%= link_to "投稿一覧へ", boards_path, class: "text-blue-500 underline" %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container mx-auto pt-3">
<!-- 投稿するボタン -->
<div class="my-3 p-3 border border-white bg-white">
  <a href="/boards/new" class="w-full py-2 px-4 bg-white text-gray-900 font-semibold rounded-md shadow hover:bg-gray-200 inline-block text-center">投稿する</a>
</div>

  <!-- 掲示板一覧 -->
  <div class="flex">
    <div class="w-full">
      <div class="flex flex-wrap">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container mx-auto py-8">
  <div class="flex justify-center">
    <div class="w-full lg:w-2/3">
      <h1 class="text-3xl font-bold mb-6 text-center text-gray-800"><%= t('.title') %></h1>

      <%= form_with model: @board, class: "new_board card bg-base-100 shadow-lg p-6" do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <!-- 画像フィールド -->
        <div class="form-control mb-4">
          <%= f.label :board_image, class: "label text-lg text-gray-700" %>
          <%= f.file_field :board_image, class: "file-input file-input-bordered w-full", accept: 'image/*' %>
          <%= f.hidden_field :board_image_cache %>
        </div>
        
        <!-- タグ入力フィールド -->
        <div class="form-control mb-4">
          <%= f.label :tag_list, "タグ（カンマ区切りで入力）", class: "label text-lg text-gray-700" %>
          <%= f.text_field :tag_list, class: "input input-bordered w-full", placeholder: "例: キーボード, HHKB, ホワイト" %>
        </div>

        <!-- 内容（おすすめポイント）フィールド -->
        <div class="form-control mb-4">
          <%= f.label :body, class: "label text-lg text-gray-700" %>
          <%= f.text_area :body, class: "textarea textarea-bordered w-full", placeholder: "例: デザインが好き！コスパが良い！〇〇な機能性が良いなど！" %>
        </div>        



        <!-- 送信ボタン -->
        <div class="form-control">
          <%= f.submit "投稿する", class: "btn btn-primary w-full" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class='container mx-auto px-4'>
  <div class='md:w-1/2 mx-auto'>
    <div class="text-left mb-4"> 
      <p class="text-sm text-gray-800"><%= @board.user.name %></p> 
    </div>

    <%= image_tag @board.board_image_url, class: 'object-contain w-full h-auto mx-auto mb-4' %>

    <!-- タグ表示部分にリンクを追加 -->
    <div class="flex flex-wrap gap-2 mb-6">
      <% @board.tag_list.each do |tag| %>
        <%= link_to boards_path(tag: tag), class: 'inline-block px-2 py-1 text-gray-800 bg-white rounded-full hover:bg-gray-100 text-sm' do %>
          <%= tag %>
        <% end %>
      <% end %>
    </div>

    <div class='text-left mb-6'>
      <p class='mb-6 text-sm'>
        <%= @board.body %>
      </p>
    </div>
  
    <% if current_user == @board.user %>
      <%= link_to '編集', edit_board_path(@board), class: 'btn btn-primary' %>
      <%= link_to '削除', board_path(@board), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
    <% end %>

    <div class='flex flex-col items-center mb-6'> 
      <!-- Xでシェアのボタン -->
      <div class="mb-4 flex justify-end"> 
        <%= link_to "Xでシェア", 
                    "https://twitter.com/intent/tweet?text=#{CGI.escape('Best Buy!')}&url=#{CGI.escape(board_url(@board))}&hashtags=BestBuyGadgets,RUNTEQ祭", 
                    target: '_blank', 
                    class: 'inline-block px-2 py-1 text-gray-800 bg-white rounded-full hover:bg-gray-100 text-sm' %>
      </div>
    </div>
  </div>
</div>
  
    <!-- 作成日時 -->
    <div class="text-center mb-4">
      <%= l @board.created_at, format: '%Y/%m/%d %H:%M' %>
    </div>
  
    <!-- 投稿一覧へのリンク -->
    <div class='text-center'>
      <%= link_to "投稿一覧へ", boards_path, class: "text-blue-500 underline" %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-theme="mytheme">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Best Buy Gadgets</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module' %>
  
  <!-- OGP Meta Tags -->
  <meta property="og:title" content="Best Buy Gadgets">
  <meta property="og:type" content="website">
  <meta property="og:url" content="<%= request.original_url %>">
  <meta property="og:image" content="<%= asset_url('ogp.png') %>">
  <meta property="og:description" content="お気に入りのガジェットを投稿するアプリ">
  <meta property="og:site_name" content="Best Buy Gadgets">
  <meta property="twitter:card" content="summary_large_image">
</head>


<body class="bg-white-100">
  <% if logged_in? %>
    <%= render 'shared/header', class: "bg-white shadow" %>
    <main class="container mx-auto p-4">
  <% else %>
    <%= render 'shared/before_login_header' %>
    <main class="container mx-auto p-4">
  <% end %>
  <%= render 'shared/flash_message' %>
  <%= yield %>
  </main>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="bg-base-100 shadow-md" data-theme="mytheme">
  <nav class="navbar bg-base-100 z-10 relative py-1">
    <div class="flex-1">
      <%= link_to '/', class: 'btn btn-ghost' do %>
        <span class="text-lg font-bold">Best Buy Gadgets</span>
      <% end %>
    </div>
    <div class="flex-none ml-auto">
      <ul class="menu menu-horizontal px-4 flex items-center space-x-4">
        <li><%= link_to t('header.posts'), boards_path, class: 'btn btn-ghost' %></li>
        <li><%= link_to t('header.login'), login_path, class: 'btn btn-ghost' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-error text-error-content border border-error-content p-4 rounded-md">
    <ul class="list-disc list-inside mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="mt-2">
    <div class="px-4 py-2 text-sm rounded-md 
                <%= message_type == 'success' ? 'bg-success text-success-content' : 'bg-error text-error-content' %>">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" data-theme="mytheme" class="bg-base-100 text-neutral-dark py-1 mt-2">
  <div class="container mx-auto text-center">
    <div class="flex flex-col">
      <div class="w-full">
        <div class="text-center">
          <p>&copy; <%= Time.current.year %> Best Buy Gadgets - ALL right reserved</p>
        </div>
      </div>
      <div class="w-full mt-2">
        <div class="text-center">
          <p>
            <a href="https://x.com/yuta_RUNTEQ" class="text-primary hover:underline">お問い合わせ</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-base-100 shadow-md" data-theme="mytheme">
  <nav class="navbar bg-base-100 p-1">
  <div class="flex-1">
      <%= link_to '/', class: 'btn btn-ghost' do %>
     <span class="text-lg font-bold">Best Buy Gadgets</span>
  <% end %>
</div>
    <div class="flex-none">
      <ul class="menu menu-horizontal p-2">
        <li><%= link_to t('header.posts'), boards_path, class: 'btn btn-ghost' %></li>
        <li><%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしてもよろしいですか？" }, class: 'btn btn-ghost' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class="hero min-h-screen mb-0 flex items-center justify-center" style="background-image: url('<%= asset_path 'top.jpg' %>'); background-size: cover; background-position: center;">
  <div class="max-w-md text-center">
    <h1 class="mb-5 text-3xl sm:text-4xl md:text-5xl font-bold">Best Buy Gadgets</h1>
    <p class="mb-5">お気に入りのガジェットを共有しよう！</p>
    <%= link_to '投稿を見る', boards_path, class: "btn bg-white text-black hover:bg-gray-300 transition-colors" %>
    <% if logged_in? %>
     <%= link_to 'はじめる', boards_path, class: "btn bg-white text-black hover:bg-gray-300 transition-colors" %>
    <% else %>
      <%= link_to 'はじめる', login_path, class: "btn bg-white text-black hover:bg-gray-300 transition-colors" %>
    <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<header class="bg-base-100 shadow-md" data-theme="mytheme">
  <div class="container mx-auto p-4">
    <div class="max-w-lg mx-auto">
      <h1 class="text-2xl font-bold mb-6">ログイン</h1>
      <%= form_with url: login_path, html: { class: 'space-y-4' } do |f| %>
        <div>
          <%= f.label :email, class: "label" %>
          <%= f.email_field :email, class: "input input-bordered w-full" %>
        </div>
        <div>
          <%= f.label :password, class: "label" %>
          <%= f.password_field :password, class: "input input-bordered w-full" %>
        </div>
        <%= f.submit class: "btn btn-primary w-full bg-gray-200 text-gray-800 hover:bg-gray-300 hover:text-gray-900 border-gray-200 hover:border-gray-300" %>
      <% end %>
      <div class="text-center mt-4">
        <%= link_to t('.to_register_page'), new_user_path, class: "link link-primary" %>
      </div>
    </div>
  </div>
</header>

app/views/users/new.html.erb
<header class="bg-base-100 shadow-md" data-theme="mytheme">
  <div class="container mx-auto p-4">
    <div class="max-w-lg mx-auto">
      <h1 class="text-2xl font-bold mb-6"><%= t('users.new.title') %></h1>
      <%= form_with model: @user do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <!-- ユーザー名フィールド -->
        <div class="mb-4">
          <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:border-primary focus:ring focus:ring-primary", placeholder: "ユーザー名は10文字以下" %>
        </div>

        <!-- メールフィールド -->
        <div class="mb-4">
          <%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
          <%= f.email_field :email, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:border-primary focus:ring focus:ring-primary", placeholder: "メールアドレスを入力" %>
        </div>

        <!-- パスワードフィールド -->
        <div class="mb-4">
          <%= f.label :password, class: "block text-sm font-medium text-gray-700" %>
          <%= f.password_field :password, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:border-primary focus:ring focus:ring-primary", placeholder: "4文字以上8文字以下" %>
        </div>

        <!-- パスワード確認フィールド -->
        <div class="mb-4">
          <%= f.label :password_confirmation, class: "block text-sm font-medium text-gray-700" %>
          <%= f.password_field :password_confirmation, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:border-primary focus:ring focus:ring-primary", placeholder: "パスワード確認" %>
        </div>

        <!-- 送信ボタン -->
        <%= f.submit class: "w-full py-2 px-4 bg-gray-200 text-gray-900 font-semibold rounded-md shadow hover:bg-gray-300" %>
      <% end %>

      <!-- ログインページへのリンク -->
      <div class="text-center mt-4">
        <%= link_to t('.to_login_page'), login_path, class: "text-primary hover:underline" %>
      </div>
    </div>
  </div>
</header>